from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Table, TableStyle, KeepInFrame
from reportlab.pdfgen import canvas

OUT='Technical_Report.pdf'; W,H=A4; M=13*mm; TOP=18*mm; BOT=16*mm; BODY_W=W-2*M; BODY_H=H-TOP-BOT
styles=getSampleStyleSheet()
BODY=ParagraphStyle('BodyDense',parent=styles['BodyText'],fontName='Helvetica',fontSize=9.15,leading=11.15,spaceAfter=4.2,alignment=TA_LEFT)
SMALL=ParagraphStyle('Small',parent=BODY,fontSize=8.2,leading=9.8,spaceAfter=3)
H1=ParagraphStyle('H1',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=14.5,leading=16,spaceBefore=2,spaceAfter=6)
H2=ParagraphStyle('H2',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=10.7,leading=12.2,spaceBefore=5,spaceAfter=3)
TITLE=ParagraphStyle('Title',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=19,leading=21,spaceAfter=5)
SUB=ParagraphStyle('Sub',parent=BODY,fontSize=9.4,leading=11.3,textColor=colors.HexColor('#333333'),spaceAfter=6)
CAP=ParagraphStyle('Cap',parent=SMALL,fontName='Helvetica-Bold',fontSize=8.1,leading=9.3)

def P(text,style=BODY): return Paragraph(text,style)
def bullets(items): return [P('• '+x,SMALL) for x in items]
def tbl(data,widths=None,fs=7.5,header=True):
    t=Table([[Paragraph(str(c),SMALL) for c in row] for row in data],colWidths=widths,repeatRows=1 if header else 0,hAlign='LEFT')
    st=[('FONTNAME',(0,0),(-1,0),'Helvetica-Bold' if header else 'Helvetica'),('FONTSIZE',(0,0),(-1,-1),fs),('LEADING',(0,0),(-1,-1),fs+1.6),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),3),('BOTTOMPADDING',(0,0),(-1,-1),3),('GRID',(0,0),(-1,-1),0.25,colors.HexColor('#b9b9b9'))]
    if header: st += [('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e9edf2')),('TEXTCOLOR',(0,0),(-1,0),colors.HexColor('#111111'))]
    for r in range(1 if header else 0,len(data)):
        if r%2==0: st.append(('BACKGROUND',(0,r),(-1,r),colors.HexColor('#f8f8f8')))
    t.setStyle(TableStyle(st)); return t

def header_footer(c,n):
    c.saveState(); c.setFillColor(colors.HexColor('#444444')); c.setFont('Helvetica-Bold',7.2)
    c.drawString(M,H-10.5*mm,'APZIVA PROJECT 3 | HUMAN RESOURCES CANDIDATE RANKING'); c.drawRightString(W-M,H-10.5*mm,'TECHNICAL REPORT')
    c.setStrokeColor(colors.HexColor('#b9b9b9')); c.setLineWidth(0.4); c.line(M,H-12*mm,W-M,H-12*mm)
    c.setFont('Helvetica',7.2); c.drawString(M,8.5*mm,'Ranking relevance, not hiring probability or employee quality'); c.drawRightString(W-M,8.5*mm,f'Page {n}'); c.restoreState()
def render_page(c,n,flowables):
    header_footer(c,n); kif=KeepInFrame(BODY_W,BODY_H,flowables,mode='shrink'); kif.canv=c; w,h=kif.wrap(BODY_W,BODY_H); kif.drawOn(c,M,BOT+(BODY_H-h)); c.showPage()

pages=[]
pages.append([
 P('Technical Report - Human Resources Candidate Ranking',TITLE),P('Duplicate-safe lexical ranking, fold-safe model selection, and recruiter-guided relevance feedback',SUB),
 P('<b>Selected Stage-1 model:</b> normalized hybrid retrieval (BM25 + word TF-IDF + character TF-IDF) with lexical overlap and HR/intent features, Ridge alpha = 10. <b>Mean grouped-CV NDCG@10 = 0.9628 +/- 0.0621; MAP@10 = 1.000; MRR = 1.000.</b>'),
 P('1. Executive summary',H1),
 P('This project develops a transparent candidate-ranking system for a small LinkedIn-style dataset. The task is search ranking rather than binary hiring classification: given an HR-oriented recruiter query, the system orders the available candidate profiles so the strongest human-judged matches appear near the top of the shortlist. The model score therefore expresses relative textual relevance to the stated search intent. It is not a hiring probability, a measure of employee quality, or a prediction of future job performance.'),
 P('The source contains 104 candidate rows, but repeated records reduce the effective modelling unit to 53 unique profile groups. Human relevance is graded on a 0-3 ordinal scale. Duplicate copies remain traceable through their source IDs, but model development and evaluation use the unique profile group as the unit of evidence. This prevents repeated source rows from being mistaken for additional observations and prevents near-identical copies from being split across model-development folds.'),
 P('The final model was selected from a 192-configuration screen under five-fold GroupKFold. Word TF-IDF vocabulary and IDF, character TF-IDF vocabulary and IDF, and BM25 corpus statistics are fitted from training titles inside each fold before held-out profiles are scored. The best mean NDCG@10 is 0.9628 for the normalized hybrid feature set at alpha 10. Adding connection count lowers the best mean NDCG@10 to 0.9562, so network size is excluded from the final relevance model.'),
 P('A second-stage demonstration uses explicit recruiter feedback to adjust the active search with Rocchio relevance feedback. The final Stage-2 score preserves 65% of the Stage-1 ranking and adds 35% feedback, allowing personalization to create visible rank changes without replacing the general relevance model.'),
 P('2. Problem definition and dataset',H2),tbl([['Item','Value / treatment'],['Source rows','104'],['Unique duplicate-safe groups','53'],['Duplicate copies beyond canonical rows','51'],['Primary text field','job_title'],['Operational queries','aspiring human resources; seeking human resources'],['Human relevance target','0-3 ordinal grade'],['Primary metric','NDCG@10'],['MAP/MRR relevant threshold','grade >= 2']],[55*mm,115*mm],7.7),
 P('2.1 Human relevance rubric',H2),tbl([['Grade','Interpretation','Unique groups','Raw rows'],['0','Irrelevant to the HR search objective','17','27'],['1','Weak, adjacent, or materially mismatched intent','2','10'],['2','Clearly HR-relevant, but not strongest/direct target','28','47'],['3','Strong/direct aspiring or seeking HR match','6','20']],[15*mm,105*mm,25*mm,22*mm],7.2),
 P('The available evidence is intentionally sparse: candidate ID, job title, location, connection count, an unused source fit field, and the added relevance grade. No resume body, detailed skills inventory, tenure history, compensation signal, hiring outcome, or verified performance measure is available. The system therefore answers a deliberately narrow question: lexical relevance of the visible profile title to the two HR search intents.',SMALL)])

pages.append([
 P('3. Data integrity, duplicate handling, and text preparation',H1),P('Before modelling, the labelled file is checked against the source file. The original five source fields must agree by ID; IDs must be unique; final grades must be complete and restricted to 0-3; duplicate members must carry one consistent grade; and the grouping procedure must reproduce 53 unique profiles. These ordinary data-quality safeguards protect the ranking pipeline from silent source drift.'),
 P('3.1 Duplicate-safe grouping',H2),P('A stable group key is formed from normalized job title, normalized location, and parsed connection count. All rows sharing that key are treated as one profile for model selection and ranking evaluation. GroupKFold receives the stable key as its grouping variable, so copies of a profile cannot be split between training and validation in the same fold.'),
 tbl([['Duplicate count per group','Number of groups','Rows represented'],['1','39','39'],['2','2','4'],['4','5','20'],['5','3','15'],['6','2','12'],['7','2','14'],['Total','53','104']],[65*mm,55*mm,48*mm],7.7),P('Repeated profile examples',H2),
 tbl([['Canonical ID','Copies','Profile identity','Grade'],['1','7','2019 C.T. Bauer College of Business Graduate ... aspiring Human Resources professional','2'],['7','7','Student at Humber College and Aspiring Human Resources Generalist','2'],['3','6','Aspiring Human Resources Professional - Raleigh-Durham','3'],['4','6','People Development Coordinator at Ryan - Denton, Texas','1'],['2','5','Native English Teacher at EPIK - Kanada','0'],['6','5','Aspiring Human Resources Specialist - Greater New York City Area','3']],[22*mm,18*mm,110*mm,16*mm],6.9),
 P('<b>Why grouping matters.</b> If repeated rows were treated as independent observations, a model could see an almost identical candidate during training and appear to perform well when another copy was evaluated. Collapsing the evidence to 53 groups makes the evaluation unit match the amount of unique candidate information while preserving source IDs for traceability.'),
 P('3.2 Connection-count treatment',H2),P('The connection field is parsed numerically for diagnostics and for one optional feature bundle. Values written as 500+ are represented as 500 in the numeric transformation; 44 source rows and 18 unique groups take this capped value. Across the 104 rows the parsed count ranges from 1 to 500, with median 193 and upper quartile 500. Connection count is not retained in the selected Stage-1 model because the best connection-inclusive configuration underperforms the selected text-only configuration.'),
 P('3.3 Text normalization',H2),tbl([['Operation','Treatment / rationale'],['Case and punctuation','Lowercase text; normalize punctuation and repeated whitespace.'],['HR abbreviation','Expand standalone HR to human resources in the normalized representation.'],['Entry-level variants','Normalize entry-level / entry level to entrylevel.'],['Intent vocabulary','Preserve aspiring, seeking, student, internship, entry, and entrylevel terms.'],['Sensitivity screen','Compare surface, normalized, and Porter2-stemmed preprocessing variants.']],[48*mm,120*mm],7.2),P('Normalization is deliberately conservative: it improves comparability of short titles without inventing qualifications that are absent from the source data.',SMALL)])

pages.append([
 P('4. Fold-safe evaluation architecture',H1),P('The main methodological requirement is that held-out profile text must not influence the lexical statistics used to evaluate that profile. Accordingly, each cross-validation fold fits retrieval representations only on the training profile titles. Validation titles are transformed or scored using the training-fitted representation; they are not used to estimate vocabulary, inverse-document frequency, document frequency, or average document length.'),
 P('4.1 Five-fold grouped split',H2),tbl([['Fold','Training groups','Validation groups','Training query-profile rows','Validation query-profile rows'],['1','42','11','84','22'],['2','42','11','84','22'],['3','42','11','84','22'],['4','43','10','86','20'],['5','43','10','86','20']],[17*mm,33*mm,36*mm,46*mm,42*mm],7.0),P('Each unique profile contributes one row per operational query, producing 106 query-profile observations before folding. The two rows for the same profile always remain on the same side of a split because the stable profile key is the GroupKFold grouping variable.'),
 P('4.2 Per-fold representation and scoring sequence',H2),tbl([['Step','Operation performed inside a fold'],['1','Split 53 unique profile groups with GroupKFold.'],['2','Fit word TF-IDF on training titles only.'],['3','Fit character TF-IDF on training titles only.'],['4','Fit BM25 document-frequency and document-length statistics on training titles only.'],['5','Transform recruiter queries and held-out titles with the training-fitted TF-IDF spaces; score BM25 using training-corpus statistics.'],['6','Construct retrieval, lexical-overlap, HR-overlap, intent-overlap, and optional connection features for training and validation rows.'],['7','Fit StandardScaler + Ridge on training feature rows.'],['8','Predict validation rows; calculate NDCG, MAP, and MRR by query; average the query metrics within each fold/configuration.']],[16*mm,153*mm],7.0),
 P('4.3 Why corpus-only fitting matters',H2),P('TF-IDF and BM25 are unsupervised representations, but their statistics still depend on the text corpus. Fitting them on all 53 titles before cross-validation would allow held-out titles to influence the IDF/vocabulary and BM25 statistics used to score those same profiles. The cleaned evaluation avoids this transductive dependence when estimating unseen-profile ranking quality.'),
 P('4.4 Query handling and final fit',H2),P('The two queries - aspiring human resources and seeking human resources - are transformed against each training-fitted representation. In TF-IDF, the training corpus determines vocabulary and IDF; the query is transformed afterward. In BM25, the training corpus determines document frequency and length normalization while the query supplies the terms to score. After configuration selection, the final Stage-1 system is fitted on all 53 development profiles because its purpose is then to rank the full candidate pool, not to estimate another held-out score.'),
 P('Evaluation invariants',H2),tbl([['Invariant','Required behavior'],['Duplicate isolation','Every source copy of a profile remains on the same side of a fold.'],['Corpus-statistic isolation','Validation titles do not influence TF-IDF vocabulary/IDF or BM25 document statistics.'],['Query consistency','The same two recruiter intents are evaluated in every fold.'],['Metric consistency','All configurations use the same metric implementations and grade >=2 relevance threshold.']],[48*mm,120*mm],7.1)])

pages.append([
 P('5. Retrieval representations and engineered ranking features',H1),P('Each query-profile pair is represented by transparent lexical evidence. The design combines retrieval scores with explicit overlap and intent features rather than relying on one opaque similarity measure. This improves explainability and lets model selection test which kinds of lexical evidence contribute useful ranking information.'),
 P('5.1 Retrieval representations',H2),tbl([['Representation','Construction','Technical role'],['Word TF-IDF','Word unigrams and bigrams with sublinear TF; cosine similarity.','Captures token-level alignment and short multiword phrases.'],['Character TF-IDF','Character n-grams (3-5) inside word boundaries; cosine similarity.','Adds robustness to spelling, morphology, abbreviations, and partial overlap.'],['BM25','Probabilistic term matching using k1=1.5, b=0.75.','Weights rarer query terms and normalizes for title length.'],['Hybrid','BM25 + word TF-IDF + character TF-IDF.','Lets Ridge combine complementary retrieval evidence.']],[35*mm,72*mm,61*mm],6.9),
 P('5.2 Engineered lexical and intent features',H2),tbl([['Feature','Definition / interpretation'],['jaccard','|query tokens intersect title tokens| / |query tokens union title tokens|.'],['containment','Fraction of query tokens present in the candidate title.'],['hr_overlap','Coverage of HR-specific query terms: human, resource, resources, hr, hris.'],['intent_overlap','Coverage of intent terms: aspiring, seeking, student, internship, entry, entrylevel.'],['log_connections','log(1 + parsed connection count); tested only in the optional connection bundle.']],[38*mm,130*mm],7.2),
 P('5.3 BM25 scoring detail',H2),P('For a query term t and document d, BM25 uses a smoothed inverse-document-frequency weight together with term frequency saturation and document-length normalization. With k1=1.5 and b=0.75, repeated query terms receive diminishing returns while long titles do not automatically dominate simply because they contain more tokens. Importantly, document frequency and average document length are estimated from the training corpus inside each fold.'),
 P('5.4 TF-IDF detail',H2),P('Word TF-IDF captures direct lexical matching and useful short phrases such as human resources, while character TF-IDF provides a softer surface-matching signal for short, noisy titles. Both vectorizers use training titles to learn their spaces. Queries and validation titles are transformed afterward. Cosine similarity then produces a retrieval score on a common directional scale.'),
 P('5.5 Feature bundles and linear combination',H2),P('The model screen tests retrieval-only, overlap-oriented, intent-oriented, and combined feature bundles. Ridge regression is used as the supervised combiner because the dataset is small and the engineered features already express domain-relevant evidence. StandardScaler is fitted within the training fold before Ridge so feature magnitudes do not implicitly determine coefficient importance.'),
 P('Why a linear model is appropriate here',H2),P('With only 53 unique labelled profiles, a high-capacity nonlinear learner would add variance faster than information. Ridge gives stable shrinkage, deterministic fitting, interpretable feature direction, and a compact hyperparameter search. The model is therefore deliberately matched to the evidence scale rather than optimized for architectural complexity.'),P('A strong candidate can score well through multiple routes: direct word overlap, robust character overlap, BM25 emphasis on informative query terms, and explicit intent coverage. A profile that merely contains generic HR language but lacks aspiring/seeking intent can remain relevant without automatically outranking a more direct target.',SMALL)])

pages.append([
 P('6. Model search, metrics, and selection protocol',H1),P('The broad experiment crosses preprocessing, retrieval representation, feature bundle, and Ridge regularization. The search covers <b>3 preprocessing variants x 4 representation families x 4 feature bundles x 4 Ridge penalties = 192 configurations</b>, including 64 Porter2-stemmed variants. Every configuration is evaluated on the same grouped folds and with the same metric functions.'),
 P('6.1 Search dimensions',H2),tbl([['Dimension','Values / treatment'],['Preprocessing','surface; normalized; Porter2'],['Representation family','BM25; word TF-IDF; character TF-IDF; hybrid'],['Feature bundle','retrieval; overlap; intent; combined overlap + intent'],['Ridge regularization','four broad-screen penalty values'],['Follow-up alpha tuning','0.01, 0.1, 1, 10, 100 around the retained family'],['Connection test','selected text features with and without log_connections']],[44*mm,124*mm],7.2),
 P('6.2 Ranking metrics',H2),tbl([['Metric','What it measures','Role'],['NDCG@10','Rewards placing higher 0-3 relevance grades near the top; discounts lower ranks.','Primary selection metric.'],['MAP@10','Uses grades 2-3 as relevant and measures precision of early relevant results.','Secondary metric; near saturation.'],['MRR','Reciprocal rank of the first grade >=2 result.','Secondary early-hit metric; saturates here.']],[30*mm,98*mm,40*mm],7.0),P('NDCG@10 is primary because it preserves the ordinal 0-3 target rather than collapsing grades 2 and 3. MAP@10 and MRR remain useful checks, but both are less discriminating once the first-page shortlist is already dominated by relevant candidates.'),
 P('6.3 Aggregation and selection',H2),P('For each fold/configuration, metrics are calculated separately for each of the two operational queries and then averaged. Fold means are then summarized across five folds. Selection prioritizes mean NDCG@10, with MAP@10 and MRR used as secondary evidence. The final configuration is also checked for stability, connection-count dependence, and interpretability before the all-data Stage-1 fit.'),
 P('6.4 Statistical baseline comparison',H2),P('The direct BM25-versus-word-TF-IDF comparison is paired at the fold/query level. The observed mean difference is +0.0168 NDCG@10 in favor of BM25, but the paired t-test gives p=0.278 and a 95% confidence interval of [-0.0161, +0.0498], with win/tie/loss 3/6/1. This does not establish a clear population-level superiority claim. The result is therefore treated as comparative evidence rather than proof that one retrieval family universally dominates.'),
 P('6.5 Small-data selection discipline',H2),P('Repeated experimentation on 53 unique profiles can overfit the evaluation process itself even when each fold is technically isolated. The report therefore separates configuration screening from business claims, avoids interpreting tiny metric differences as durable causal effects, and recommends a prospective holdout or recruiter pilot before production conclusions.'),P('Tie handling and determinism',H2),P('Ranking uses stable ordering and deterministic preprocessing/model fitting. Where normalized scores are equal, deterministic row ordering prevents random rank flips. This matters in a small corpus where several short titles can produce nearly identical retrieval evidence.',SMALL)])

pages.append([
 P('7. Model-selection results and quantitative comparison',H1),P('The corrected fold-safe screen selects the normalized hybrid retrieval representation with overlap and intent features, Ridge alpha=10. The selected family combines all three retrieval signals with Jaccard, containment, HR overlap, and intent overlap, while excluding connection count.'),
 P('7.1 Selected configuration',H2),tbl([['Configuration','Mean NDCG@10','SD','MAP@10','MRR'],['Selected normalized hybrid + overlap/intent, alpha 10','0.9628','0.0621','1.000','1.000'],['Best connection-inclusive model','0.9562','0.0649','1.000','1.000'],['Character TF-IDF baseline','0.9535','0.0582','0.9938','1.000'],['BM25 baseline','0.9527','0.0577','0.9909','1.000'],['Word TF-IDF baseline','0.9359','0.0668','0.9874','1.000']],[82*mm,27*mm,18*mm,22*mm,18*mm],7.0),
 P('7.2 Practical effect size',H2),P('Relative to the direct baselines, the selected model improves mean NDCG@10 by roughly +0.0093 versus character TF-IDF, +0.0101 versus BM25, and +0.0269 versus word TF-IDF. These are useful directional improvements, but the small number of unique profiles and fold-level variability argue against overstating precision.'),
 P('7.3 Why connection count is excluded',H2),P('The best text-plus-connections variant reaches 0.9562, below the selected text-only model at 0.9628. Connection count is also an undesirable relevance shortcut: it reflects network size rather than direct query alignment and may proxy tenure, geography, industry, or platform activity. Excluding it improves the selected metric and reduces a potential fairness/governance concern.'),
 P('7.4 Interpreting saturated MAP and MRR',H2),P('MAP@10 and MRR are both 1.000 for the selected model. This does not mean the problem is solved perfectly. Those metrics binarize relevance at grade >=2 or examine only the first relevant hit; they do not distinguish a grade-3 candidate from a grade-2 candidate once both count as relevant. NDCG@10 remains more informative because it preserves graded relevance and discounts rank position.'),
 P('7.5 BM25 versus word TF-IDF',H2),tbl([['Statistic','Result'],['Mean paired NDCG@10 difference (BM25 - word TF-IDF)','+0.0168'],['Paired t-test p-value','0.278'],['95% confidence interval','[-0.0161, +0.0498]'],['Win / tie / loss','3 / 6 / 1']],[92*mm,76*mm],7.3),P('The interval crosses zero and the p-value is not small. The correct conclusion is that BM25 has a modest observed advantage in this sample, but the evidence is not strong enough to claim a general superiority. The hybrid model benefits from combining complementary signals instead of forcing a single-representation winner narrative.'),
 P('7.6 Selection conclusion',H2),P('The retained Stage-1 model is therefore: normalized titles; BM25 + word TF-IDF + character TF-IDF retrieval scores; Jaccard, containment, HR overlap, and intent overlap; StandardScaler; Ridge alpha=10; no connection-count feature. The configuration is then fitted on all 53 labelled profile groups to create the final corpus ranking.',SMALL)])

pages.append([
 P('8. Final Stage-1 ranking and score interpretation',H1),P('After configuration selection, the representation spaces and Ridge model are fitted using all 53 development profile groups. Each profile is scored for both operational queries. Query-level predictions are normalized and aggregated to produce one Stage-1 score per unique profile. Duplicate source IDs map back to the same canonical group, preventing repeated profiles from occupying multiple independent positions in the model-development ranking.'),
 P('8.1 Top Stage-1 profiles',H2),tbl([['Rank','Canonical ID','Profile title','Grade','Stage-1 score'],['1','99','Seeking Human Resources Position','2','1.0000'],['2','3','Aspiring Human Resources Professional - Raleigh-Durham','3','0.9770'],['3','97','Aspiring Human Resources Professional - Kokomo','2','0.9770'],['4','6','Aspiring Human Resources Specialist','3','0.9559'],['5','28','Seeking Human Resources Opportunities','3','0.9286'],['6','73','Aspiring Human Resources Manager, seeking internship in HR','3','0.9034'],['7','10','Seeking Human Resources HRIS and Generalist Positions','3','0.8924'],['8','72','Business Management Major and Aspiring Human Resources Manager','2','0.8508'],['9','100','Aspiring HR Manager | Seeking Entry-Level HR Position','2','0.8417'],['10','27','Aspiring HR Management student seeking an internship','3','0.8261']],[13*mm,21*mm,103*mm,14*mm,22*mm],6.55),
 P('8.2 Score semantics',H2),P('Stage-1 scores are normalized ranking scores, not probabilities. A score of 1.0 means the profile sits at the top of the current corpus after the selected scoring and aggregation procedure; it does not mean 100% probability of suitability or hiring success. Differences should be interpreted as relative ordering evidence within this candidate pool.'),
 P('8.3 Explainability',H2),P('The final score can be decomposed into a small set of understandable inputs: BM25, word TF-IDF, character TF-IDF, Jaccard overlap, query containment, HR-term overlap, and intent-term overlap. This supports recruiter-facing explanations such as direct phrase alignment, coverage of the search intent, or strong HR-term match without making claims beyond the available title text.'),
 P('8.4 Ranking stability and ties',H2),P('IDs 3 and 97 have the same displayed Stage-1 score after rounding because both titles normalize to aspiring human resources professional. They remain distinct profile groups because location and connection metadata differ in the duplicate grouping key. Stable ranking logic provides deterministic ordering when scores tie or nearly tie.'),
 P('8.5 Output structure',H2),P('The ranking output retains canonical ID, member source IDs, title, location, duplicate count, human relevance grade for offline evaluation, Stage-1 score, and Stage-1 rank. Human grades are evaluation/development targets and should not be surfaced to recruiters as if they were objective employment-quality labels.'),P('Operational interpretation',H2),P('Stage 1 should be treated as a shortlist-ordering aid. A recruiter still reviews the underlying candidate information, applies job-specific requirements that are not encoded here, and can provide explicit feedback for the active search. The system is intentionally designed to support rather than replace human screening judgement.',SMALL)])

pages.append([
 P('9. Stage-2 recruiter relevance feedback',H1),P('Stage 2 demonstrates how explicit recruiter feedback can personalize the active search after the general Stage-1 model has produced a stable baseline. The demonstration stars source ID 3 and rejects no candidates. The source ID is resolved to its unique profile group before feedback is applied, so duplicate handling remains consistent.'),
 P('9.1 Rocchio parameters and blend',H2),tbl([['Component','Value / role'],['Initial query vector weight (alpha)','1.00'],['Starred / relevant centroid weight (beta)','0.75'],['Rejected / nonrelevant centroid weight (gamma)','0.15'],['Stage-1 contribution to final Stage-2 score','65%'],['Feedback contribution to final Stage-2 score','35%'],['Demonstration starred ID','3'],['Demonstration rejected IDs','none']],[78*mm,90*mm],7.3),P('Rocchio shifts the query representation toward language present in starred profiles and, when rejected profiles exist, away from their centroid. In this demonstration the rejected set is empty, so only the positive feedback term changes the query. The resulting feedback similarity is normalized and blended with Stage 1 rather than replacing it.'),
 P('9.2 Stage-2 top results',H2),tbl([['Stage-2 rank','Canonical ID','Profile title','Stage-1 rank','Rank change'],['1','3','Aspiring Human Resources Professional - Raleigh-Durham','2','+1'],['2','97','Aspiring Human Resources Professional - Kokomo','3','+1'],['3','99','Seeking Human Resources Position','1','-2'],['4','6','Aspiring Human Resources Specialist','4','0'],['5','73','Aspiring Human Resources Manager, seeking internship in HR','6','+1'],['6','74','Human Resources Professional','11','+5'],['7','28','Seeking Human Resources Opportunities','5','-2'],['8','10','Seeking HRIS and Generalist Positions','7','-1'],['9','72','Business Management Major and Aspiring HR Manager','8','-1'],['10','100','Aspiring HR Manager | Seeking Entry-Level HR Position','9','-1']],[23*mm,21*mm,91*mm,20*mm,18*mm],6.55),
 P('9.3 Rank-shift behavior',H2),P('The starred profile ID 3 becomes rank 1, its closely matching duplicate-title counterpart ID 97 moves to rank 2, and the original Stage-1 leader ID 99 shifts to rank 3. Elsewhere in the full ranking, profiles with language similar to the starred candidate can move materially: ID 76 moves from 28 to 20 (+8), ID 1 from 27 to 21 (+6), and ID 74 from 11 to 6 (+5). These movements illustrate that feedback is active while the 65% baseline weight prevents complete reordering.'),
 P('9.4 Feedback controls',H2),P('Feedback should be explicit, session- or search-scoped, auditable, and reversible. A star/reject action should not silently become a permanent global label. The system should log which profiles were starred or rejected, the parameter values used, the pre- and post-feedback ranks, and the search context that generated the action.'),P('Human grades are not recruiter feedback',H2),P('The 0-3 relevance grades are the supervised development target for Stage 1. They are not silently reused as Stage-2 preferences. Stage 2 consumes only explicit user actions supplied to the feedback function, preserving a clear separation between offline evaluation labels and interactive personalization.',SMALL)])

pages.append([
 P('10. Limitations, governance, and next steps',H1),P('The project demonstrates a sound small-data ranking workflow, but the evidence base remains limited. The most important constraint is not lack of model complexity; it is the quantity, breadth, and reliability of unique labelled profiles. The current results should be read as offline ranking evidence for this dataset and these two search intents.'),
 P('10.1 Technical limitations',H2),*bullets(['Only 53 unique labelled profiles support model selection and evaluation; uncertainty remains high despite 104 source rows.','The relevance target is based on human judgement and no formal inter-rater agreement estimate is available.','Profile evidence is dominated by short job-title text; deeper semantic equivalence and qualification detail can be missed.','The two operational queries are narrow and may not represent other HR searches, seniority levels, industries, or geographies.','Repeated experimentation on a small development set can overfit the evaluation process even when folds are correctly isolated.','Offline NDCG/MAP/MRR do not prove recruiter productivity, hiring quality, retention, or employee performance.']),
 P('10.2 Fairness and responsible use',H2),P('Removing explicit protected attributes does not establish fairness. Job-title wording, location, career seniority, and network-related metadata can still correlate with protected characteristics or opportunity. Connection count is excluded from the selected model both because it reduces NDCG@10 and because it is a weak relevance proxy with potential representational concerns. Any deployment should examine subgroup behavior using appropriately governed data and should preserve recruiter review and appeal/override mechanisms.'),
 P('10.3 Recommended next steps',H2),tbl([['Priority','Action','Purpose'],['1','Collect substantially more unique labelled profiles and additional recruiter queries.','Increase evidence breadth and reduce variance.'],['2','Use at least two annotators on a subset; measure agreement and resolve rubric ambiguities.','Quantify label reliability.'],['3','Create a prospective holdout set not used during configuration screening.','Measure generalization after development choices are frozen.'],['4','Run a controlled recruiter pilot with time-to-shortlist and judgement-quality outcomes.','Connect offline ranking metrics to business value.'],['5','Evaluate semantic embeddings only after the stronger labelled benchmark exists.','Test added complexity against a stable reference.'],['6','Add fairness monitoring, feedback audit logs, and search-level rollback controls.','Support responsible operation.']],[17*mm,75*mm,76*mm],6.7),
 P('10.4 Reproduction and repository structure',H2),P('The submitted repository is intentionally flat. Install the pinned packages from requirements.txt, launch Jupyter from the repository root, and execute 01_data_representation.ipynb, 02_grouped_cv_model_selection.ipynb, and 03_final_ranking_stage2.ipynb in numerical order. The notebooks use the two CSV files beside them and contain the executed outputs needed to reproduce the data checks, grouped model search, final ranking, and feedback demonstration.'),
 P('10.5 Technical conclusion',H2),P('The final system is a compact, interpretable candidate ranker matched to the scale of the evidence. Duplicate-safe profile grouping defines the true evaluation unit; fold-local TF-IDF/BM25 fitting keeps held-out profile text out of representation estimation; systematic grouped model selection identifies a normalized hybrid Ridge model with NDCG@10 0.9628; connection count is excluded; and Rocchio feedback provides controlled personalization anchored 65% to the Stage-1 baseline. The next improvement should come from more unique, consistently labelled data and prospective evaluation rather than from increasing model complexity alone.'),P('Final retained configuration: normalized hybrid lexical retrieval + overlap/intent features; Ridge alpha=10; no connection-count feature. Primary grouped-CV result: NDCG@10 0.9628 +/- 0.0621.',CAP)])

c=canvas.Canvas(OUT,pagesize=A4); c.setTitle('Technical Report - Human Resources Candidate Ranking'); c.setAuthor('Apziva Project 3'); c.setSubject('Duplicate-safe lexical ranking, grouped model selection, and recruiter relevance feedback')
for i,flow in enumerate(pages,1): render_page(c,i,flow)
c.save(); print(f'Wrote {OUT} with {len(pages)} pages')
